version: '3'

services:
  db:
    build:
      context: docker/db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./:/code
      - ./docker/db/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      POSTGRES_PASSWORD: example
      DATABASE_URL_ROOT: postgres://postgres:example@db:5432/postgres
      COMICSTOR_POSTGRAPHQL_PASSWORD: xyz
  api:
    build:
      context: docker/api
    volumes:
      - ./:/code
      - ./docker/api/entrypoint.sh:/usr/local/bin/entrypoint.sh
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://comicstor_postgraphql:xyz@db:5432/postgres
      PORT: 5000

volumes:
  db-data:
